# Browser
if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

# Editors
export EDITOR='vim'
export VISUAL='code'
export PAGER='less'

# Language
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# Paths
# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

# Less
# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#################
# .zprofile
#################

export PATH=/usr/local/bin:$PATH

# zsh-completions
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi

# openssl
export PATH="/usr/local/opt/openssl/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"

# nodebrew
export PATH=$HOME/.nodebrew/current/bin:$PATH

# pyenv Python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# rbenv Ruby
eval "$(rbenv init -)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/google-cloud-sdk/completion.zsh.inc"; fi

export PATH="/usr/local/opt/php@7.3/bin:$PATH"
export PATH="/usr/local/opt/php@7.3/sbin:$PATH"

# Composer
export PATH="$HOME/.composer/vendor/bin:$PATH"

# fzf
export FZF_DEFAULT_COMMAND='rg --files --hidden'
# fzf - completion
export FZF_COMPLETION_TRIGGER='**'
export FZF_COMPLETION_OPTS='--border --info=inline'
_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}
_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}
_fzf_comprun() {
  local command=$1
    shift

  case "$command" in
    cd)           fzf "$@" --preview 'tree -C {} | head -200' ;;
    export|unset) fzf "$@" --preview "eval 'echo \$'{}" ;;
    ssh)          fzf "$@" --preview 'dig {}' ;;
    *)            fzf "$@" ;;
    esac
}

# git [alias]
alias g='git'
alias ga='git add'
alias gs='git status'
alias gc='git commit'
alias gch='git checkout'
alias gp='git push'
alias gpull='git pull'
alias gd='git diff'
alias gf='git fetch --all --tags --prune'
alias gl='git log --graph --color --all --oneline'

# lazygit
alias lg='lazygit'

# ctags [alias]
alias ctags="`brew --prefix`/bin/ctags"

# delete ds_store [alias]
alias delds='find . -name ".DS_Store" -print -exec rm {} ";"'

# ripgrep [alias]
alias rgf='rg --files | rg'
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

# CURL [alias]
alias curl_header='curl -D - -s'

# grep [alias]
alias grepa='grep --color=auto -r --exclude-dir={node_modules,.git} --line-number --with-filename'
alias grepl='grep --color=auto -r -l --exclude-dir={node_modules,.git} --line-number --with-filename'
alias grepc='grep --count --color=auto -r --exclude-dir={node_modules,.git} --line-number --with-filename'

# vim [alias]
alias vimn='vim -u NONE -N'
alias mvimn='mvim -u NONE'
alias nimn='nvim -u NONE -N'

# dotfiles [alias]
alias dotfiles='mvim ~/'

# fzf [alias]
alias fzfp='fzf --preview "bat --color=always --style=header,grid --line-range :100 {}"'
alias fzfv='nvim `fzfp`'
alias fzfd='nvim $(dirname `fzfp`)'
alias fzfcd='cd $(dirname `fzfp`)'

alias server='browser-sync start --server --files "**/*.html,**/*.js,**/*.css"'

# SourceTree [alias]
alias s='stree .'

# ps [alias]
alias psg='ps -e | grep'

# Chrome [alias]
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

# devel [alias]
alias devl='git fetch &&git status -bs && nvim ./ && npm run dev'
alias devel='git fetch &&git status -bs && chrome && nvim ./ && npm run dev'

# find
alias lla='ll -d $(find `pwd`)'
alias findd='find . -type d'
alias findf='find . -type f'

# cd
alias home='cd ~/'
alias yama='cd ~/yama-dev/'
alias yamadev='cd ~/yama-dev/'

